/**
 * Single import surface for lucide-react-taro (per-icon paths for tree-shaking).
 * Do not import from `lucide-react-taro` elsewhere — enforced by ESLint + verify:bundle.
 *
 * Per-icon modules bundle isolated React contexts, so app-level LucideTaroProvider cannot
 * set defaults. Apply defaultColor here instead (see createLucideIcon.ts).
 */
export { DEFAULT_LUCIDE_ICON_COLOR, withDefaultIconColor } from './createLucideIcon';
export { LucideTaroProvider } from './LucideTaroProvider';

import { withDefaultIconColor } from './createLucideIcon';
import { AudioWaveform as AudioWaveformIcon } from 'lucide-react-taro/icons/audio-waveform';
import { BedDouble as BedDoubleIcon } from 'lucide-react-taro/icons/bed-double';
import { Bell as BellIcon } from 'lucide-react-taro/icons/bell';
import { Bookmark as BookmarkIcon } from 'lucide-react-taro/icons/bookmark';
import { Bot as BotIcon } from 'lucide-react-taro/icons/bot';
import { Calendar as CalendarIcon } from 'lucide-react-taro/icons/calendar';
import { CalendarDays as CalendarDaysIcon } from 'lucide-react-taro/icons/calendar-days';
import { Car as CarIcon } from 'lucide-react-taro/icons/car';
import { Check as CheckIcon } from 'lucide-react-taro/icons/check';
import { ChevronDown as ChevronDownIcon } from 'lucide-react-taro/icons/chevron-down';
import { ChevronLeft as ChevronLeftIcon } from 'lucide-react-taro/icons/chevron-left';
import { ChevronRight as ChevronRightIcon } from 'lucide-react-taro/icons/chevron-right';
import { ChevronUp as ChevronUpIcon } from 'lucide-react-taro/icons/chevron-up';
import { CircleCheck as CircleCheckIcon } from 'lucide-react-taro/icons/circle-check';
import { Clock as ClockIcon } from 'lucide-react-taro/icons/clock';
import { FileText as FileTextIcon } from 'lucide-react-taro/icons/file-text';
import { Flame as FlameIcon } from 'lucide-react-taro/icons/flame';
// import { Globe as GlobeIcon } from 'lucide-react-taro/icons/globe';
import { House as HouseIcon } from 'lucide-react-taro/icons/house';
import { Image as ImageIconBase } from 'lucide-react-taro/icons/image';
import { Info as InfoIcon } from 'lucide-react-taro/icons/info';
import { List as ListIcon } from 'lucide-react-taro/icons/list';
import { Lock as LockIcon } from 'lucide-react-taro/icons/lock';
import { LogOut as LogOutIcon } from 'lucide-react-taro/icons/log-out';
import { Map as MapIcon } from 'lucide-react-taro/icons/map';
import { MapPin as MapPinIcon } from 'lucide-react-taro/icons/map-pin';
import { Megaphone as MegaphoneIcon } from 'lucide-react-taro/icons/megaphone';
import { MessageCircle as MessageCircleIcon } from 'lucide-react-taro/icons/message-circle';
import { MessageSquare as MessageSquareIcon } from 'lucide-react-taro/icons/message-square';
import { Minus as MinusIcon } from 'lucide-react-taro/icons/minus';
import { Music2 as Music2Icon } from 'lucide-react-taro/icons/music-2';
import { Plane as PlaneIcon } from 'lucide-react-taro/icons/plane';
import { Plus as PlusIcon } from 'lucide-react-taro/icons/plus';
import { RefreshCw as RefreshCwIcon } from 'lucide-react-taro/icons/refresh-cw';
import { RotateCcw as RotateCcwIcon } from 'lucide-react-taro/icons/rotate-ccw';
import { ScanLine as ScanLineIcon } from 'lucide-react-taro/icons/scan-line';
import { Search as SearchIcon } from 'lucide-react-taro/icons/search';
import { Send as SendIcon } from 'lucide-react-taro/icons/send';
import { Share2 as Share2Icon } from 'lucide-react-taro/icons/share-2';
import { Shield as ShieldIcon } from 'lucide-react-taro/icons/shield';
import { ShieldAlert as ShieldAlertIcon } from 'lucide-react-taro/icons/shield-alert';
import { Sparkles as SparklesIcon } from 'lucide-react-taro/icons/sparkles';
import { Star as StarIcon } from 'lucide-react-taro/icons/star';
import { Ticket as TicketIcon } from 'lucide-react-taro/icons/ticket';
import { Trash2 as Trash2Icon } from 'lucide-react-taro/icons/trash-2';
import { TrendingUp as TrendingUpIcon } from 'lucide-react-taro/icons/trending-up';
import { TriangleAlert as TriangleAlertIcon } from 'lucide-react-taro/icons/triangle-alert';
import { User as UserIcon } from 'lucide-react-taro/icons/user';
import { Users as UsersIcon } from 'lucide-react-taro/icons/users';
import { Utensils as UtensilsIcon } from 'lucide-react-taro/icons/utensils';
import { X as XIcon } from 'lucide-react-taro/icons/x';
import { Zap as ZapIcon } from 'lucide-react-taro/icons/zap';

export const AudioWaveform = withDefaultIconColor(AudioWaveformIcon);
export const BedDouble = withDefaultIconColor(BedDoubleIcon);
export const Bell = withDefaultIconColor(BellIcon);
export const Bookmark = withDefaultIconColor(BookmarkIcon);
export const Bot = withDefaultIconColor(BotIcon);
export const Calendar = withDefaultIconColor(CalendarIcon);
export const CalendarDays = withDefaultIconColor(CalendarDaysIcon);
export const Car = withDefaultIconColor(CarIcon);
export const Check = withDefaultIconColor(CheckIcon);
export const ChevronDown = withDefaultIconColor(ChevronDownIcon);
export const ChevronLeft = withDefaultIconColor(ChevronLeftIcon);
export const ChevronRight = withDefaultIconColor(ChevronRightIcon);
export const ChevronUp = withDefaultIconColor(ChevronUpIcon);
export const CircleCheck = withDefaultIconColor(CircleCheckIcon);
export const Clock = withDefaultIconColor(ClockIcon);
export const FileText = withDefaultIconColor(FileTextIcon);
export const Flame = withDefaultIconColor(FlameIcon);
export const Globe = withDefaultIconColor(FlameIcon); // TODO: Fix Globe icon import
export const House = withDefaultIconColor(HouseIcon);
export const ImageIcon = withDefaultIconColor(ImageIconBase);
export const Info = withDefaultIconColor(InfoIcon);
export const List = withDefaultIconColor(ListIcon);
export const Lock = withDefaultIconColor(LockIcon);
export const LogOut = withDefaultIconColor(LogOutIcon);
export const Map = withDefaultIconColor(MapIcon);
export const MapPin = withDefaultIconColor(MapPinIcon);
export const Megaphone = withDefaultIconColor(MegaphoneIcon);
export const MessageCircle = withDefaultIconColor(MessageCircleIcon);
export const MessageSquare = withDefaultIconColor(MessageSquareIcon);
export const Minus = withDefaultIconColor(MinusIcon);
export const Music2 = withDefaultIconColor(Music2Icon);
export const Plane = withDefaultIconColor(PlaneIcon);
export const Plus = withDefaultIconColor(PlusIcon);
export const RefreshCw = withDefaultIconColor(RefreshCwIcon);
export const RotateCcw = withDefaultIconColor(RotateCcwIcon);
export const ScanLine = withDefaultIconColor(ScanLineIcon);
export const Search = withDefaultIconColor(SearchIcon);
export const Send = withDefaultIconColor(SendIcon);
export const Share2 = withDefaultIconColor(Share2Icon);
export const Shield = withDefaultIconColor(ShieldIcon);
export const ShieldAlert = withDefaultIconColor(ShieldAlertIcon);
export const Sparkles = withDefaultIconColor(SparklesIcon);
export const Star = withDefaultIconColor(StarIcon);
export const Ticket = withDefaultIconColor(TicketIcon);
export const Trash2 = withDefaultIconColor(Trash2Icon);
export const TrendingUp = withDefaultIconColor(TrendingUpIcon);
export const TriangleAlert = withDefaultIconColor(TriangleAlertIcon);
export const User = withDefaultIconColor(UserIcon);
export const Users = withDefaultIconColor(UsersIcon);
export const Utensils = withDefaultIconColor(UtensilsIcon);
export const X = withDefaultIconColor(XIcon);
export const Zap = withDefaultIconColor(ZapIcon);
